### ISSUE TITLE
Using with typescript

### ISSUE THREAD

**Issue by qWici** [KnorpelSenf/telegraf-session-firestore#5]
Can someone give me a hint on how to use this library with Typescript so that it does not complain about missing property

![image](https://user-images.githubusercontent.com/11472929/142471275-891f947f-dbe0-4386-ab47-666341fc0e69.png)
@KnorpelSenf

**Comment by KnorpelSenf** [comment]
This has nothing to do specifically with this library. You should look into how you can define custom properties on the context object in Telegraf. Use this to make sure `ctx.session` exists and the error will go away.
